import { Router, type IRouter } from "express";
import healthRouter from "./health";
import configRouter from "./config";
import sheetsRouter from "./sheets";
import enrollmentsRouter from "./enrollments";
import rolesRouter from "./roles";
import adminRouter from "./admin";
import principalsRouter from "./principals";
import usersRouter from "./users";
import tutorsRouter from "./tutors";
import subjectsRouter from "./subjects";
import announcementsRouter from "./announcements";
import scheduleCalendarRouter from "./scheduleCalendar";
import enrollmentRequestsRouter from "./enrollmentRequests";
import pushRouter from "./push";
import attendanceRouter from "./attendance";
import backupRouter from "./backup";
import settingsRouter from "./settings";
import githubSyncStatusRouter from "./githubSyncStatus";
import analysisRouter from "./analysis";

const router: IRouter = Router();

router.use(healthRouter);
router.use(configRouter);
router.use(sheetsRouter);
router.use(enrollmentsRouter);
router.use(rolesRouter);
router.use(adminRouter);
router.use(principalsRouter);
router.use(usersRouter);
router.use(tutorsRouter);
router.use(subjectsRouter);
router.use(announcementsRouter);
router.use(scheduleCalendarRouter);
router.use(enrollmentRequestsRouter);
router.use(pushRouter);
router.use(attendanceRouter);
router.use(backupRouter);
router.use(settingsRouter);
router.use(githubSyncStatusRouter);
router.use(analysisRouter);

export default router;
